####################################### Services
services:
  github-backup:
    image: ahmettoguz/github-backup:v1.0.0
    container_name: github-backup-c
    env_file:
      - ./.env
    volumes:
      - ./backup:/app/backup